MODE: predict # test, if you are predicting on the test set / predict, if you are predicting on unnanotated images (completely new area)
PATCH_SIZE: 512
OVERLAP: 0
MEDIAN_FILTER_SIZE: 30
BOUNDARY_WIDTH: 50
